name: Test Build Anaconda3 and Miniconda3 Images
on:
  push:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/ana_minconda_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/debian/Dockerfile'
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/ana_minconda_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [anaconda3, miniconda3]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/s390x,linux/arm-64,linux/amd-64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: network=host

      - name: test-build ${{ matrix.type }}/debian
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.type }}/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./${{ matrix.type }}/debian/Dockerfile
          tags: continuumio/${{ matrix.type }}/debian:latest
          platforms: linux/s390x,linux/arm-64,linux/amd-64
