name: Build and publish Windows package builder images
on:
  push:
    tags:
      - 'pkg-build-*'
    paths:
      - 'anaconda-pkg-build/windows/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_win.yml'
  pull_request:
    paths:
      - 'anaconda-pkg-build/windows/Dockerfile'
      - '.github/workflows/anaconda_pkg_build_win.yml'
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch,suffix=-nanoserver
            type=ref,event=pr,suffix=-nanoserver
            type=match,pattern=miniconda3-v(.*)-nanoserver,group=1,suffix=-nanoserver
          flavor: |
            latest=false

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96
      #   with:
      #     images: |
      #       public.ecr.aws/y0o4y9o3/anaconda-pkg-build
      #     tags: |
      #       type=ref,event=branch,suffix=-windows
      #       type=ref,event=pr,suffix=-windows
      #       type=match,pattern=pkg-build-(.*),group=1,suffix=-windows

      # The build push action does not support windows builds yet,
      # thus using raw commands https://github.com/docker/build-push-action/issues/18
      # TODO: Parse and use the meta action generated tag list
      - name: Build
        run: |
          # echo "${{ steps.meta.outputs.tags }}"
          cd anaconda-pkg-build/windows/ && docker build . -t continuumio/anaconda-pkg-build:master-windows && docker image inspect continuumio/anaconda-pkg-build:master-windows