name: Build and Publish Conda CI Images
on:
  schedule:
    - cron:  '0 0 * * 0'
  push:
    paths:
      - 'conda_ci/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: network=host

      - name: build-push conda-ci-linux-64-python3.8
        uses: docker/build-push-action@v2
        with:
          context: ./conda_ci/conda-ci-linux-64-python3
          builder: ${{ steps.buildx.outputs.name }}
          file: ./conda_ci/conda-ci-linux-64-python3/Dockerfile
          build-args: PYTHON_VERSON=3.8
          tags: continuumio/conda-ci-linux-64-python3.8:latest
          push: true 

      - name: build-push conda-ci-linux-64-python3.7
        uses: docker/build-push-action@v2
        with:
          context: ./conda_ci/conda-ci-linux-64-python3
          builder: ${{ steps.buildx.outputs.name }}
          file: ./conda_ci/conda-ci-linux-64-python3/Dockerfile
          build-args: PYTHON_VERSON=3.7
          tags: continuumio/conda-ci-linux-64-python3.7:latest
          push: true

      - name: build-push conda-ci-linux-64-python2.7
        uses: docker/build-push-action@v2
        with:
          context: ./conda_ci/conda-ci-linux-64-python2.7
          builder: ${{ steps.buildx.outputs.name }}
          file: ./conda_ci/conda-ci-linux-64-python2.7/Dockerfile
          tags: continuumio/conda-ci-linux-64-python2.7:latest
          push: true 
