name: Build and Publish Conda CI Images
on:
  schedule:
    - cron:  '0 0 * * 0'
  pull_request:
    paths:
      - 'conda_ci/**'
      - '.github/workflows/conda_ci_cicd.yml'
  push:
    paths:
      - 'conda_ci/**'
      - '.github/workflows/conda_ci_cicd.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Login to DockerHub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
        with:
          version: latest
          driver-opts: network=host

      - name: build-push conda-ci-linux-64-python3.9
        uses: docker/build-push-action@0987321e128873c0caa3bed11ad3b83f22b846ed
        with:
          context: ./conda_ci/conda-ci-linux-64-python3
          builder: ${{ steps.buildx.outputs.name }}
          file: ./conda_ci/conda-ci-linux-64-python3/Dockerfile
          build-args: PYTHON_VERSION=3.9
          tags: continuumio/conda-ci-linux-64-python3.9:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: build-push conda-ci-linux-64-python3.8
        uses: docker/build-push-action@0987321e128873c0caa3bed11ad3b83f22b846ed
        with:
          context: ./conda_ci/conda-ci-linux-64-python3
          builder: ${{ steps.buildx.outputs.name }}
          file: ./conda_ci/conda-ci-linux-64-python3/Dockerfile
          build-args: PYTHON_VERSION=3.8
          tags: continuumio/conda-ci-linux-64-python3.8:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: build-push conda-ci-linux-64-python3.7
        uses: docker/build-push-action@0987321e128873c0caa3bed11ad3b83f22b846ed
        with:
          context: ./conda_ci/conda-ci-linux-64-python3
          builder: ${{ steps.buildx.outputs.name }}
          file: ./conda_ci/conda-ci-linux-64-python3/Dockerfile
          build-args: PYTHON_VERSION=3.7
          tags: continuumio/conda-ci-linux-64-python3.7:latest
          push: ${{ github.ref == 'refs/heads/master' }}
